language: java

jdk:
- openjdk11

if: NOT commit_message =~ ^\[Tycho\].*$
install: "/bin/true"

jobs:
  include:
  - script: xvfb-run ./mvnw --settings ./.travis/settings.xml clean verify $(if [[ $TRAVIS_TAG =~ ^v.* ]]; then echo "-Prelease-composite"; fi) -B
    after_success:
    - bash <(curl -s https://codecov.io/bash)
    before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=v$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
    deploy:
      provider: releases
      api_key:
        secure: bxWMgyh6HDdQoGKcAR9VjNmort+5zQ+bYG2Rs/Z3k9utuEwuSOxPA2N7+A2ufe9pNsIFVFhceWDi/pGSfs0Qp+upBZnfxNw27SDT7ntcsR6SmuUh5Nqc4GQQB6iwXhwIAOSsoosOgCacm72hnD6idEj+e9D2eX80q5HWOqK7myduiRgTxE9rBLMuQQZTVUJXQu3Ut9LqT4k2HrheMQzf8toXjbSPxSP78A5ilnYftds81gDdQzbxHU4NhFvipGDrxLIRK3t6qi1MFYf5WxkHiueaoKNLiMZbbww2DhdiU41hJdn96w+9ZXu9y96l4OYCeeMHIm6zEcnKQuL/YOagVOLGoO7qcznslh2X+PUzHDC5NUO02+ive8IuT4bGz0HoPblAlvAPyEt1ErjAtZGnKh6EMUrXVYG0eWKIymL9/dr4WfCapxv+y7gnOJSHmE02hKa847mkvGXvqCVvXXK2bGPvbQL3Y/2rXwij5++v3cpGymo03UohjQAKQ6CWqqBglb2rG80zgFwhWaSrDJkEkZX356u85mAPqf6h14VPfWAhY5ILN6BzzFMJVjv7j1Iuyeebf8yYA7pNm8bfBYsl2BrhEvbhgiQ/Df6vGTS5B/KRI4o71MlXJzablaQpdTshDq0ADemwNWR4tcxjzd/1rXilFYy68HjMIfwP1wLaMmQ=
      file_glob: true
      file:
      - "./**/target/*.jar"
      - org.contextmapper.dsl.repository/target/org.contextmapper.dsl.repository-*.zip
      skip_cleanup: true
      on:
        tags: true
      name: "$project_version"
  - script: ./gradlew clean build $(if [[ $TRAVIS_TAG =~ ^v.* || ($TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == 'false') ]]; then echo "publish -Psigning.keyId=${GPG_KEY_ID} -Psigning.password=${GPG_KEY_PASSPHRASE}"; fi)

before_install:
- sudo apt-get -y install graphviz
- openssl aes-256-cbc -K $encrypted_324cf7253e32_key -iv $encrypted_324cf7253e32_iv
  -in secret-key.gpg.enc -out secret-key.gpg -d

